---
# os_prometheus_aodh_autoscaling / tasks / main.yml
# ==============================================================================
# Main Task Execution Sequence
# ==============================================================================

- name: Gather prerequisites, directories and install libvirt-exporter
  ansible.builtin.import_tasks: prerequisites.yml
  tags: [prerequisites, autoscaling]

- name: Install and configure Prometheus server
  ansible.builtin.import_tasks: prometheus.yml
  tags: [prometheus, autoscaling]

- name: Install and start Server Group Exporter
  ansible.builtin.import_tasks: exporter.yml
  tags: [exporter, autoscaling]

- name: Configure OpenStack Aodh for Prometheus integration
  ansible.builtin.import_tasks: aodh.yml
  tags: [aodh, autoscaling]