---
# handlers/main.yml

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Restart server-group-exporter
  ansible.builtin.systemd:
    name: server-group-exporter
    state: restarted

- name: Restart aodh-evaluator
  ansible.builtin.systemd:
    name: aodh-evaluator
    state: restarted
  failed_when: false

- name: Restart aodh-notifier
  ansible.builtin.systemd:
    name: aodh-notifier
    state: restarted
  failed_when: false